apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-e
rules:
- apiGroups:
  - apps.openshift.io
  - ''
  resources:
  - deploymentconfigs/scale
  verbs:
  - update
- apiGroups:
  - ''
  resources:
  - pods/exec
  verbs:
  - get