apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: isp-developer9
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - replicationcontrollers/scale
  verbs:
  - update
- apiGroups:
  - extensions
  resources:
  - deployments/scale
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - update
